import type { ConvertOptions, ProxyNode } from '@subbridge/core'
import { normalizeSsPlugin, safeLineName } from './plugin'
import {
  AUTO_GROUP,
  appRuleUrl,
  collectSets,
  FALLBACK_GROUP,
  FINAL_GROUP,
  fastlyIcon,
  finalDefaultsDirect,
  INTERNET_TEST_URL,
  MAIN_GROUP,
  orderedSets,
  PROXY_TEST_URL,
  QX_LOON_ICONS,
  type RulePreset,
  rulesForPreset,
  STRATEGY_ICONS,
  selectorGroupsForPreset,
  selectorOptions,
} from './policy'

/**
 * Loon node lines (`[Proxy]` style) — also what a Loon `[Remote Proxy]`
 * subscription consumes. Supported: Shadowsocks (obfs), VMess, VLESS (TLS /
 * ws / REALITY), Trojan, Hysteria2. TUIC and gRPC/H2/HTTPUpgrade transports
 * are skipped rather than emitted as dead entries.
 */
export function toLoonNodes(nodes: ProxyNode[]): string {
  return nodes
    .map((n) => loonLine({ ...n, name: safeLineName(n.name) }))
    .filter((l): l is string => l !== null)
    .join('\n')
}

/**
 * Full Loon profile following the unified Matrix policy. When `resources`
 * are supplied (the worker passes per-set node-subscription URLs), nodes come
 * in through `[Remote Proxy]` so they refresh on their own; otherwise they are
 * written inline under `[Proxy]`.
 */
export function toLoonConfig(nodes: ProxyNode[], options: ConvertOptions = {}): string {
  const testUrl = options.testUrl ?? PROXY_TEST_URL
  const useRules = options.rules !== 'none'
  const preset: RulePreset =
    options.rules === 'lite' || options.rules === 'full' ? options.rules : 'default'
  const useAuto = options.urlTest !== false
  const useFallback = options.fallback !== false
  const safe = nodes.map((n) => ({ ...n, name: safeLineName(n.name) }))
  const resources = options.resources ?? []
  const remote = resources.length > 0

  // Loon groups may list remote-subscription names directly; a remote name
  // must differ from the group names, hence the "-Sub" suffix.
  const subName = (tag: string) => `${tag}-Sub`
  const sets = orderedSets(collectSets(safe), options.setStrategies)
  const setNames = sets.map((s) => s.name)
  const lines = remote ? [] : safe.map(loonLine).filter((l): l is string => l !== null)
  const inlineNames = remote ? [] : lines.map((l) => l.slice(0, l.indexOf(' = ')))
  const allMembers = remote ? resources.map((r) => subName(r.tag)) : inlineNames
  const membersOf = (set: string, members: string[]) =>
    remote ? [subName(set)] : members.filter((m) => inlineNames.includes(m))
  const poolNames = setNames.length > 0 ? setNames : allMembers
  const icon = (url: string | undefined) => (url ? `,img-url=${url}` : '')
  const loonPolicy = (p: string) => p

  const out: string[] = [
    '# Generated by SubBridge — https://github.com/wandonwe/SubBridge',
    '',
    '[General]',
    'ip-mode = dual',
    'skip-proxy = 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,100.64.0.0/10,169.254.0.0/16,224.0.0.0/4,240.0.0.0/4,255.255.255.255,localhost,*.local',
    'bypass-tun = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.168.0.0/16,198.18.0.0/15,224.0.0.0/4,255.255.255.255/32',
    'dns-server = 119.29.29.29',
    'doh-server = https://doh.pub/dns-query',
    'real-ip = *.msftconnecttest.com,*.msftncsi.com,*.srv.nintendo.net,*.stun.playstation.net,xbox.*.microsoft.com,*.xboxlive.com,stun.l.google.com,localhost.ptlogin2.qq.com',
    'allow-wifi-access = false',
    'allow-udp-proxy = true',
    `proxy-test-url = ${testUrl}`,
    `internet-test-url = ${INTERNET_TEST_URL}`,
    'test-timeout = 5',
    'interface-mode = auto',
    '',
  ]
  if (remote) {
    out.push('[Remote Proxy]')
    for (const r of resources) {
      out.push(`${subName(r.tag)} = ${r.url},parser-enabled=false,udp=true,enabled=true`)
    }
  } else {
    out.push('[Proxy]', ...lines)
  }
  out.push('', '[Proxy Group]')

  out.push(
    `${MAIN_GROUP} = select,${[
      ...(useAuto ? [AUTO_GROUP] : []),
      ...(useFallback ? [FALLBACK_GROUP] : []),
      ...poolNames,
      'DIRECT',
    ].join(',')}${icon(QX_LOON_ICONS[MAIN_GROUP])}`,
  )
  if (useRules) {
    for (const g of selectorGroupsForPreset(preset)) {
      // Loon has no REJECT-DROP policy.
      const opts = finalDefaultsDirect(
        g,
        selectorOptions(g, setNames)
          .filter((o) => o !== 'REJECT-DROP')
          .map(loonPolicy),
      )
      out.push(`${g.name} = select,${opts.join(',')}${icon(QX_LOON_ICONS[g.name])}`)
    }
  }
  if (useAuto && allMembers.length > 0) {
    out.push(
      `${AUTO_GROUP} = url-test,${allMembers.join(',')},url = ${testUrl},interval = 600,tolerance = 50${icon(QX_LOON_ICONS[AUTO_GROUP])}`,
    )
  }
  // Fail over across the node feeds themselves (in set order) when remote.
  const fallbackMembers = remote ? allMembers : poolNames
  if (useFallback && fallbackMembers.length > 0) {
    out.push(
      `${FALLBACK_GROUP} = fallback,${fallbackMembers.join(',')},url = ${testUrl},interval = 600,max-timeout = 5000${icon(QX_LOON_ICONS[FALLBACK_GROUP])}`,
    )
  }
  for (const set of sets) {
    const members = membersOf(set.name, set.members)
    if (members.length === 0) continue
    const ic = icon(fastlyIcon(STRATEGY_ICONS[set.strategy]))
    if (set.strategy === 'auto') {
      out.push(
        `${set.name} = url-test,${members.join(',')},url = ${testUrl},interval = 600,tolerance = 50${ic}`,
      )
    } else if (set.strategy === 'fallback') {
      out.push(
        `${set.name} = fallback,${members.join(',')},url = ${testUrl},interval = 600,max-timeout = 5000${ic}`,
      )
    } else {
      out.push(`${set.name} = select,${members.join(',')}${ic}`)
    }
  }

  out.push('', '[Remote Rule]')
  if (useRules) {
    for (const entry of rulesForPreset(preset)) {
      if (!entry.surgePath) continue
      out.push(
        `${appRuleUrl('Loon', entry.surgePath)}, policy=${entry.policy}, tag=${entry.key}, enabled=true`,
      )
    }
  }
  out.push('', '[Rule]')
  if (useRules) {
    out.push(
      'DOMAIN-SUFFIX,home.arpa,DIRECT',
      'DOMAIN-SUFFIX,invalid,DIRECT',
      'GEOIP,CN,DIRECT',
      `FINAL,${FINAL_GROUP}`,
    )
  } else {
    out.push(`FINAL,${MAIN_GROUP}`)
  }
  out.push('')
  return out.join('\n')
}

function q(s: string): string {
  return `"${s.replace(/"/g, '')}"`
}

/** One Loon `[Proxy]` line, or null when Loon can't carry the node. */
function loonLine(node: ProxyNode): string | null {
  const t = node.transport?.type ?? 'tcp'
  if (t !== 'tcp' && t !== 'ws') return null
  const tls = node.tls
  const parts: string[] = []
  const transport = () => {
    parts.push(`transport=${t}`)
    if (t === 'ws') {
      if (node.transport?.path) parts.push(`path=${node.transport.path}`)
      if (node.transport?.host) parts.push(`host=${node.transport.host}`)
    }
  }
  const tlsOpts = (always = false) => {
    if (!tls?.enabled && !always) return
    if (node.protocol !== 'trojan') parts.push('over-tls=true')
    if (tls?.serverName) parts.push(`sni=${tls.serverName}`)
    if (tls?.insecure) parts.push('skip-cert-verify=true')
    if (tls?.reality) {
      parts.push(`public-key=${q(tls.reality.publicKey)}`)
      if (tls.reality.shortId) parts.push(`short-id=${tls.reality.shortId}`)
    }
    const fp = tls?.fingerprint || (tls?.reality ? 'chrome' : undefined)
    if (fp === 'chrome' || fp === 'safari') {
      parts.push(`tls-profile=${fp === 'chrome' ? 'chrome' : 'safari-ios-26'}`)
    }
  }

  switch (node.protocol) {
    case 'ss': {
      if (t !== 'tcp') return null
      parts.push(
        `${node.name} = Shadowsocks`,
        node.server,
        String(node.port),
        node.method,
        q(node.password),
      )
      const plugin = normalizeSsPlugin(node)
      if (plugin?.kind === 'obfs') {
        parts.push(`obfs-name=${plugin.mode}`)
        if (plugin.host) parts.push(`obfs-host=${plugin.host}`)
      } else if (plugin) {
        return null
      }
      break
    }
    case 'vmess': {
      if (tls?.reality) return null
      parts.push(
        `${node.name} = vmess`,
        node.server,
        String(node.port),
        vmessCipher(node.security),
        q(node.uuid),
      )
      transport()
      parts.push(`alterId=${node.alterId || 0}`)
      tlsOpts()
      break
    }
    case 'vless': {
      parts.push(`${node.name} = VLESS`, node.server, String(node.port), q(node.uuid))
      transport()
      if (node.flow) parts.push(`flow=${node.flow}`)
      tlsOpts()
      break
    }
    case 'trojan': {
      parts.push(`${node.name} = trojan`, node.server, String(node.port), q(node.password))
      if (t === 'ws') transport()
      tlsOpts(true)
      break
    }
    case 'hysteria2': {
      if (t !== 'tcp') return null
      parts.push(`${node.name} = Hysteria2`, node.server, String(node.port), q(node.password))
      if (tls?.serverName) parts.push(`sni=${tls.serverName}`)
      if (tls?.insecure) parts.push('skip-cert-verify=true')
      if (node.obfs === 'salamander' && node.obfsPassword) {
        parts.push(`salamander-password=${node.obfsPassword}`)
      } else if (node.obfs) {
        return null
      }
      if (node.downMbps) parts.push(`download-bandwidth=${node.downMbps}`)
      break
    }
    default:
      return null
  }
  if (node.udp || node.protocol === 'hysteria2') parts.push('udp=true')
  const [head, ...rest] = parts
  return `${head},${rest.join(',')}`
}

function vmessCipher(security: string): string {
  if (security === 'chacha20-ietf-poly1305') return 'chacha20-poly1305'
  const allowed = ['aes-128-gcm', 'chacha20-poly1305', 'none', 'auto']
  return allowed.includes(security) ? security : 'auto'
}
