import type { ConvertOptions, ProxyNode } from '@subbridge/core'
import { normalizeSsPlugin, safeLineName } from './plugin'
import {
  AUTO_GROUP,
  appRuleUrl,
  collectSets,
  FALLBACK_GROUP,
  FINAL_GROUP,
  fastlyIcon,
  MAIN_GROUP,
  orderedSets,
  PROXY_TEST_URL,
  QX_LOON_ICONS,
  type RulePreset,
  rulesForPreset,
  STRATEGY_ICONS,
  selectorGroupsForPreset,
  selectorOptions,
} from './policy'

/**
 * QX reserves `proxy` / `direct` / `reject` (case-insensitive), so the main
 * group is called Global here — same as the hand-written reference configs.
 */
const QX_MAIN = 'Global'

function qxPolicy(p: string): string | null {
  if (p === MAIN_GROUP) return QX_MAIN
  if (p === 'DIRECT') return 'direct'
  if (p === 'REJECT') return 'reject'
  if (p === 'REJECT-DROP') return null
  return p
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

/**
 * Full Quantumult X profile following the unified Matrix policy. With
 * `resources` (per-set node subscriptions supplied by the worker) nodes come
 * in through `[server_remote]` and refresh on their own; otherwise they are
 * written inline under `[server_local]`.
 */
export function toQuantumultXConfig(nodes: ProxyNode[], options: ConvertOptions = {}): string {
  const testUrl = options.testUrl ?? PROXY_TEST_URL
  const useRules = options.rules !== 'none'
  const preset: RulePreset =
    options.rules === 'lite' || options.rules === 'full' ? options.rules : 'default'
  const useAuto = options.urlTest !== false
  const useFallback = options.fallback !== false
  const resources = options.resources ?? []
  const remote = resources.length > 0
  const sets = orderedSets(collectSets(nodes), options.setStrategies)
  const setNames = sets.map((s) => s.name)
  const icon = (name: string, url = QX_LOON_ICONS[name]) => (url ? `, img-url=${url}` : '')
  // Select a node set by resource tag (remote) or by its members' names (inline).
  const byResource = (tags: string[]) => `resource-tag-regex=^(${tags.map(escapeRegex).join('|')})$`
  const byNames = (names: string[]) =>
    `server-tag-regex=^(${names.map((n) => escapeRegex(safeLineName(n))).join('|')})$`
  const setFilter = (set: { name: string; members: string[] }) =>
    remote ? byResource([set.name]) : byNames(set.members)

  const out: string[] = [
    '# Generated by SubBridge — https://github.com/wandonwe/SubBridge',
    '',
    '[general]',
    `server_check_url=${testUrl}`,
    'dns_exclusion_list=*.msftconnecttest.com, *.msftncsi.com, *.srv.nintendo.net, *.stun.playstation.net, xbox.*.microsoft.com, *.xboxlive.com, stun.l.google.com, localhost.ptlogin2.qq.com',
    'excluded_routes=127.0.0.0/8, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 100.64.0.0/10, 169.254.0.0/16, 224.0.0.0/4, 240.0.0.0/4, 255.255.255.255/32',
    'icmp_auto_reply=true',
    '',
    '[dns]',
    'doh-server=https://doh.pub/dns-query',
    'server=119.29.29.29',
    '',
    '[policy]',
  ]
  const poolNames = setNames.length > 0 ? setNames : []
  out.push(
    `static=${QX_MAIN}, ${[
      ...(useAuto ? [AUTO_GROUP] : []),
      ...(useFallback ? [FALLBACK_GROUP] : []),
      ...poolNames,
      'direct',
      // Nothing to pick from otherwise: list the nodes themselves.
      ...(useAuto || useFallback || poolNames.length > 0 ? [] : ['server-tag-regex=.*']),
    ].join(', ')}${icon(MAIN_GROUP)}`,
  )
  if (useRules) {
    for (const g of selectorGroupsForPreset(preset)) {
      const opts = selectorOptions(g, setNames)
        .map(qxPolicy)
        .filter((o): o is string => o !== null)
      out.push(`static=${g.name}, ${opts.join(', ')}${icon(g.name)}`)
    }
  }
  if (useAuto) {
    out.push(
      `url-latency-benchmark=${AUTO_GROUP}, server-tag-regex=.*, check-interval=600, tolerance=50, alive-checking=false${icon(AUTO_GROUP)}`,
    )
  }
  if (useFallback) {
    const filter = remote && setNames.length > 0 ? byResource(setNames) : 'server-tag-regex=.*'
    out.push(`available=${FALLBACK_GROUP}, ${filter}, check-interval=600${icon(FALLBACK_GROUP)}`)
  }
  for (const set of sets) {
    const ic = icon(set.name, fastlyIcon(STRATEGY_ICONS[set.strategy]))
    if (set.strategy === 'auto') {
      out.push(
        `url-latency-benchmark=${set.name}, ${setFilter(set)}, check-interval=600, tolerance=50, alive-checking=false${ic}`,
      )
    } else if (set.strategy === 'fallback') {
      out.push(`available=${set.name}, ${setFilter(set)}, check-interval=600${ic}`)
    } else {
      out.push(`static=${set.name}, ${setFilter(set)}${ic}`)
    }
  }

  out.push('', '[server_local]')
  if (!remote) out.push(toQuantumultX(nodes))
  out.push('', '[server_remote]')
  for (const r of resources) {
    out.push(`${r.url}, tag=${r.tag}, update-interval=86400, opt-parser=false, enabled=true`)
  }

  out.push('', '[filter_remote]')
  if (useRules) {
    for (const entry of rulesForPreset(preset)) {
      if (!entry.surgePath) continue
      const policy = qxPolicy(entry.policy)
      out.push(
        `${appRuleUrl('QuantumultX', entry.surgePath)}, tag=${entry.key}, force-policy=${policy}, update-interval=86400, opt-parser=false, enabled=true`,
      )
    }
  }
  out.push('', '[filter_local]')
  if (useRules) {
    out.push(
      'host-suffix, home.arpa, direct',
      'host-suffix, invalid, direct',
      'geoip, cn, direct',
      `final, ${FINAL_GROUP}`,
    )
  } else {
    out.push(`final, ${QX_MAIN}`)
  }
  out.push('', '[rewrite_remote]', '', '[rewrite_local]', '', '[task_local]', '', '[mitm]', '')
  return out.join('\n')
}

/**
 * Render a Quantumult X server snippet (`[server_local]` style lines), for
 * use as a `[server_remote]` resource. Supported: shadowsocks (obfs / ws),
 * vmess, vless (TLS / ws / REALITY, 1.5.5+), trojan. Anything QX can't carry
 * — hysteria2, tuic, gRPC/H2/HTTPUpgrade transports — is skipped rather than
 * emitted as a dead plain-TCP entry.
 */
export function toQuantumultX(nodes: ProxyNode[], _options: ConvertOptions = {}): string {
  return nodes
    .map(qxLine)
    .filter((l): l is string => l !== null)
    .join('\n')
}

function qxLine(node: ProxyNode): string | null {
  const t = node.transport?.type ?? 'tcp'
  if (t !== 'tcp' && t !== 'ws') return null

  const parts: string[] = []
  switch (node.protocol) {
    case 'ss': {
      if (t !== 'tcp') return null
      parts.push(`shadowsocks=${node.server}:${node.port}`)
      parts.push(`method=${node.method}`, `password=${node.password}`)
      const plugin = normalizeSsPlugin(node)
      if (plugin?.kind === 'obfs') {
        parts.push(`obfs=${plugin.mode}`)
        if (plugin.host) parts.push(`obfs-host=${plugin.host}`)
      } else if (plugin?.kind === 'v2ray') {
        parts.push(plugin.tls ? 'obfs=wss' : 'obfs=ws')
        if (plugin.host) parts.push(`obfs-host=${plugin.host}`)
        if (plugin.path) parts.push(`obfs-uri=${plugin.path}`)
      } else if (plugin) {
        return null
      }
      break
    }
    case 'vmess': {
      if (node.tls?.reality) return null
      parts.push(`vmess=${node.server}:${node.port}`)
      parts.push(`method=${vmessCipher(node.security)}`, `password=${node.uuid}`)
      applyObfs(parts, node)
      // QX uses the AEAD header by default; legacy alterId>0 servers need it off.
      if (node.alterId > 0) parts.push('aead=false')
      break
    }
    case 'vless': {
      parts.push(`vless=${node.server}:${node.port}`)
      parts.push('method=none', `password=${node.uuid}`)
      applyObfs(parts, node)
      const reality = node.tls?.reality
      if (reality) {
        parts.push(`reality-base64-pubkey=${reality.publicKey}`)
        if (reality.shortId) parts.push(`reality-hex-shortid=${reality.shortId}`)
      }
      if (node.flow) parts.push(`vless-flow=${node.flow}`)
      break
    }
    case 'trojan': {
      parts.push(`trojan=${node.server}:${node.port}`)
      parts.push(`password=${node.password}`)
      if (t === 'ws') {
        parts.push(node.tls?.enabled === false ? 'obfs=ws' : 'obfs=wss')
        if (node.transport?.path) parts.push(`obfs-uri=${node.transport.path}`)
        const h = node.transport?.host ?? node.tls?.serverName
        if (h) parts.push(`obfs-host=${h}`)
      } else {
        parts.push('over-tls=true')
        if (node.tls?.serverName) parts.push(`tls-host=${node.tls.serverName}`)
      }
      if (node.tls?.insecure) parts.push('tls-verification=false')
      break
    }
    default:
      return null
  }

  if (node.udp) parts.push('udp-relay=true')
  parts.push('fast-open=false', `tag=${safeLineName(node.name)}`)
  return parts.join(', ')
}

function vmessCipher(security: string): string {
  if (security === 'chacha20-ietf-poly1305') return 'chacha20-poly1305'
  const allowed = ['aes-128-gcm', 'chacha20-poly1305', 'none']
  return allowed.includes(security) ? security : 'aes-128-gcm'
}

/** vmess / vless: ws, wss or plain TLS via QX's `obfs` key. */
function applyObfs(parts: string[], node: ProxyNode): void {
  const isWs = node.transport?.type === 'ws'
  const isTls = Boolean(node.tls?.enabled)
  if (isWs) {
    parts.push(isTls ? 'obfs=wss' : 'obfs=ws')
    if (node.transport?.path) parts.push(`obfs-uri=${node.transport.path}`)
    const h = node.transport?.host ?? node.tls?.serverName
    if (h) parts.push(`obfs-host=${h}`)
  } else if (isTls) {
    parts.push('obfs=over-tls')
    if (node.tls?.serverName) parts.push(`obfs-host=${node.tls.serverName}`)
  }
  if (node.tls?.insecure) parts.push('tls-verification=false')
}
